<?php
/**
 * Created by PhpStorm.
 * User: summerctang
 * Date: 2017/10/28
 * Time: 23:51
 */
namespace App\Http\Requests\User;

use App\Http\Requests\BaseRequest;

class RegisterByPhoneRequest extends BaseRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }
}